from semsearch.share.config import Settings


def scrapy_settings(settings: Settings) -> dict[str, object]:
    return {
        "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
        "CONCURRENT_REQUESTS": settings.crawl_concurrency,
        "CONCURRENT_REQUESTS_PER_DOMAIN": 1,
        "CONCURRENT_ITEMS": settings.extraction_workers,
        "DOWNLOAD_DELAY": settings.crawl_delay_seconds,
        "DOWNLOAD_DELAY_JITTER": 0,
        "AUTOTHROTTLE_ENABLED": True,
        "AUTOTHROTTLE_START_DELAY": settings.crawl_delay_seconds,
        "AUTOTHROTTLE_TARGET_CONCURRENCY": 1.0,
        "DOWNLOAD_TIMEOUT": settings.crawl_timeout_seconds,
        "DNS_TIMEOUT": settings.crawl_timeout_seconds,
        "REDIRECT_MAX_TIMES": 5,
        "DOWNLOAD_MAXSIZE": 10 * 1024 * 1024,
        "DOWNLOAD_WARNSIZE": 5 * 1024 * 1024,
        "DOWNLOAD_VERIFY_CERTIFICATES": True,
        "DOWNLOADER_CLIENTCONTEXTFACTORY": "scrapy.core.downloader.contextfactory.BrowserLikeContextFactory",
        "DOWNLOAD_HANDLERS": {
            "http": "scrapy.core.downloader.handlers.http11.HTTP11DownloadHandler",
            "https": "scrapy.core.downloader.handlers.http11.HTTP11DownloadHandler",
            "file": None,
            "data": None,
            "ftp": None,
            "s3": None,
        },
        "TWISTED_DNS_RESOLVER": "semsearch.cli.crawl.policy.PublicResolver",
        "ROBOTSTXT_OBEY": True,
        "USER_AGENT": settings.user_agent,
        "RETRY_TIMES": 2,
        "COOKIES_ENABLED": False,
        "TELNETCONSOLE_ENABLED": False,
        "REMOTE_CONTROL_ENABLED": False,
        "HTTPPROXY_ENABLED": False,
        "METAREFRESH_ENABLED": False,
        "SCHEDULER_PRIORITY_QUEUE": "scrapy.pqueues.DownloaderAwarePriorityQueue",
        "SCHEDULER_MEMORY_QUEUE": "scrapy.squeues.FifoMemoryQueue",
        "DOWNLOADER_MIDDLEWARES": {"semsearch.cli.crawl.policy.CrawlPolicy": 560},
        "ITEM_PIPELINES": {"semsearch.cli.crawl.pipeline.ArticlePipeline": 300},
        "LOG_LEVEL": settings.log_level,
    }
